[project]
name = "pymel"
version = "1.7.1rc1"
description = "Python in Maya Done Right"
authors = [
    { name = "Chad Dombrova" },
    { name = "Paul Molodowitch" },
    { name = "Olivier Renouard" },
]
requires-python = ">=3.10"
readme = "README.md"
license = "BSD"
keywords = [
    "maya",
    "mel",
    "3d",
    "graphics",
    "games",
    "VFX",
    "CG",
    "animation",
]

[project.urls]
Homepage = "https://github.com/Lumapictures/pymel"
Repository = "https://github.com/Lumapictures/pymel"

[project.scripts]
ipymel = "pymel.tools.ipymel:main"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "sphinx>=8.1.0",
    "jinja2>=3.1.6",
    "sphinx_rtd_theme>=3.0.2",
    "sphinxcontrib-jquery>=4.1",
    "beautifulsoup4>=4.8.2,<5",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["pymel"]
module-root = ""

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
# this is the default pattern for matching tags, but excluding the leading 'v'.
# we could omit this if we started prefixing our tags with 'v'
pattern = '''
(?x)                                                (?# ignore whitespace)
^(?P<base>\d+\.\d+\.\d+)                            (?# e.g., v1.2.3)
(-?((?P<stage>[a-zA-Z]+)\.?(?P<revision>\d+)?))?    (?# e.g., beta-0)
(\+(?P<tagged_metadata>.+))?$                       (?# e.g., +linux)
'''

[build-system]
requires = ["poetry>=1.10.0", "poetry-dynamic-versioning"]
build-backend = "poetry.masonry.api"
